version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.go
    ports:
      - "9090:9090"
  web:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app
